// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "hOQOPOOOOOO'#Ca'#CaQQOPOOOOOO-E6_-E6_",
  stateData: "]~OQPORPOSPO~O",
  goto: "]UPPPPPVQQORRQ",
  nodeNames: "⚠ File Identifier Number String",
  maxTerm: 6,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!Z~RTrsb!Q![s!c!}{#R#S{#T#o{~eROrbrsns~b~sOS~~xPR~!Q![s~!QRQ~!c!}{#R#S{#T#o{",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
